config/routes.rb
Vavant::Application.routes.draw do
  resources :materials

  mount Ckeditor::Engine => '/ckeditor'

  mount Ckeditor::Engine => "/ckeditor"

  get "courses/authored" => 'courses#authored', :as => 'courses_authored'
  get "courses/registered" => 'courses#registered', :as => 'courses_registered'

  get "courses/register/:course_id" => 'courses#register', :as => 'courses_register'
  get "courses/showdetail/:course_id" => 'courses#showdetail', :as => 'courses_showdetail'
  get "courses/changestatus" => 'courses#changestatus', :as => 'courses_changestatus'
  get "courses/mark_complete/:course_id" => 'courses#mark_complete', :as => 'courses_mark_complete'
  get "courses/mark_incomplete/:course_id" => 'courses#mark_incomplete', :as => 'courses_mark_incomplete'

  get "tags/:tag" => 'home#index', :as => 'tag'

  get "lessons/associate_material" => 'lessons#associate_material', :as => 'lessons_associate_material'
  get "lessons/mark_complete/" => 'lessons#mark_complete', :as => 'lessons_mark_complete'
  get "lessons/mark_incomplete/" => 'lessons#mark_incomplete', :as => 'lessons_mark_incomplete'
  get "lessons/display_lesson" => 'lessons#display_lesson', :as => 'lessons_display_lesson'

  resources :courses

  resources :reviews

  resources :registrations

  resources :lessons

  resources :collections

  resources :languages

  devise_for :users

  root :to => 'home#index'

  get "home/userinfo" => 'home#userinfo', :as => 'home_userinfo'
end

app/models/lesson.rb
include AutoHtml

class Lesson < ActiveRecord::Base
  belongs_to :course
  has_many :completions, :dependent => :destroy

  has_attached_file :material

  validates :description, :presence => true
  validates :title, :presence => true, :length => {:in => 1..80}
  validates :course_id, :presence => true

  attr_accessible :course_id, :description, :sequence, :title, :material

  before_create :set_sequence

  ##before_destroy :check_destroy_allowed

  ## make sure upon sequence is setup correctly upon creation
  def set_sequence
    maxseq = Lesson.where(:course_id => self.course_id).maximum("sequence")
    if (maxseq.nil?)
      maxseq = 0
    end
    self.sequence = maxseq + 1
  end

  def check_destroy_allowed
    course = Course.find(self.course_id)
    return course.check_destroy_allowed
  end

  def self.lessons_by_courses(course_id)
    return Lesson.where("course_id = ?", course_id)
  end

  def description_html_version
    return auto_html(self.description){
                                      image;
                                      dailymotion;
                                      google_video;
                                      metacafe;
                                      soundcloud;
                                      google_map;
                                      vimeo;
                                      youtube;
                                      simple_format; link(:target => 'blank');
                                      }
  end

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index]

  def index
    @course_id   = params[:course_id]
    @course_title = params[:course_title]
    @lessons = Lesson.lessons_by_courses(params[:course_id])
  end

  def associate_material
    @lesson = Lesson.find(params[:lesson_id])
    materials = Array.new(1)
    materials[0] = params[:material_id]
    @lesson.material_ids = materials

    if @lesson.save
      redirect_to(edit_lesson_path(@lesson), :notice => 'Material successfully associated.')
    else
      redirect_to(edit_lesson_path(@lesson))
    end
  end

  def show
      @lesson = Lesson.find(params[:id])
  end

  def mark_complete
    @completion = Completion.find(:all, :conditions => ["course_id = ? and user_id = ? and lesson_id = ?", params[:course_id], current_user.id, params[:lesson_id]])
    if (@completion.empty?)
      @completion = Completion.new(:user_id => current_user.id, :course_id => params[:course_id], :lesson_id => params[:lesson_id], :status => 2)
      if @completion.save

          redirect_to(lessons_display_lesson_path(:course_id => params[:course_id], :lesson_id => params[:lesson_id]), :notice => 'Lesson has been mark completed')
      end
    else
      @completion[0].status = 2
      if @completion[0].save
          redirect_to(lessons_display_lesson_path(:course_id => params[:course_id], :lesson_id => params[:lesson_id]), :notice => 'Lesson has been mark completed')
      end
    end
  end

  def mark_incomplete
    @completion = Completion.find(:all, :conditions => ["course_id = ? and user_id = ? and lesson_id = ?", params[:course_id], current_user.id, params[:lesson_id]])
    if (@completion.empty?)
      @completion = Completion.new(:user_id => current_user.id, :course_id => params[:course_id], :lesson_id => params[:lesson_id], :status => 1)
      if @completion.save
          redirect_to(lessons_display_lesson_path(:course_id => params[:course_id], :lesson_id => params[:lesson_id]), :notice => 'Lesson has been marked in progress')
      end
    else
      @completion[0].status = 1
      if @completion[0].save
          redirect_to(lessons_display_lesson_path(:course_id => params[:course_id], :lesson_id => params[:lesson_id]), :notice => 'Lesson has been marked in progress')
      end
    end
  end

  def display_lesson
    @lesson = Lesson.find(params[:lesson_id])
    @lessons = nil

    if (params.has_key?(:course_id))
      course = Course.find(params[:course_id])
      @lessons = course.lessons
    end

    @lesson_completion = Completion.find(:all, :conditions => ["course_id = ? and user_id = ? and lesson_id = ?", course.id, current_user.id, @lesson.id])
  end

  def new
    @lesson = Lesson.new
    @lesson.course_id = params[:course_id]
    @course = Course.find(params[:course_id])
  end

  def edit
    @lesson = Lesson.find(params[:id])
    @course = Course.find(@lesson.course_id)
  end

  def create
    @lesson = Lesson.new(params[:lesson])

    if @lesson.save
      @course = Course.find(@lesson.course_id)
      redirect_to(courses_showdetail_path(@course), :notice => 'Lesson was successfully created.')
    else
      render :action => "new"
    end
  end

  def update
    @lesson = Lesson.find(params[:id])

    if @lesson.update_attributes(params[:lesson])
      @course = Course.find(@lesson.course_id)
      redirect_to(courses_showdetail_path(@course), :notice => 'Lesson was successfully updated.')
    else
      render :action => "edit"
    end

  end

  def destroy
    @lesson = Lesson.find(params[:id])
    @course = Course.find(@lesson.course_id)
    @lesson.destroy
    redirect_to(courses_showdetail_path(@course), :notice => 'Lesson was deleted.')

  end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<%= semantic_form_for @lesson, :html => { :multipart => true } do |f| %>
  <%= f.inputs do %>
    <%= f.input :title, :input_html => { :class => "span12"} %>
    <%= f.input :description, :as => :ckeditor, :input_html => { :toolbar => 'Full'} %>
    <%= f.input :course_id, :as => :hidden  %>
    <%= f.input :sequence, :as => :hidden %>
    <%= f.file_field :material %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input, :label => 'Save' %>
  <% end %>
<% end %>

app/views/lessons/display_lesson.html.erb
<div class="page-header">
<h1 class="page-title">
   <%= @lesson.title %>
</h1>
</div>

<div class="span9">
  <div class="row">
    <div class="well">
       <%= raw @lesson.description_html_version %>
    </div>

    <% if !@lesson.material_file_name.nil? %>
        <div id='my-video'></div>
        <script type='text/javascript'>
            jwplayer('my-video').setup({
                file: '<%= 'http://127.0.0.1:3000' + @lesson.material.url() %>',
                width: '700',
                height: '400'
            });
        </script>
    <% end %>
  </div>
</div>

<% if !@lessons.nil? %>
    <div class="span3">
      <div class="widget">
           <h5 class="sidebar-title">Details</h5>
           <ul class="unstyled">
               <li><i class="icon-book"></i><%= link_to @lesson.course.title, @lesson.course %></li>
               <% if @lesson_completion.empty? || @lesson_completion[0].status == 1  %>
                 <i class="icon-arrow-right"></i>In Progress
                 <li><small>(<%= link_to 'click', lessons_mark_complete_path(:course_id => @lesson.course.id, :lesson_id => @lesson.id) %> to complete</small>)</li>
               <% else %>
                 <li><i class="icon-ok"></i> on <%=  @lesson_completion[0].updated_at.to_date.to_s(:long) %></li>
                 <li><small>(<%= link_to 'click', lessons_mark_incomplete_path(:course_id => @lesson.course.id, :lesson_id => @lesson.id) %> to mark in progress</small>)</li>
               <% end %>
           </ul>
      </div>

        <div class="widget">
             <h5 class="sidebar-title">Table of Contents </h5>
             <ul class="unstyled">
              <li>
              </li>
               <% count = 1 %>
               <% @lessons.each do |l| %>
                  <li><%= link_to count.to_s() + '. ' + l.title, lessons_display_lesson_path(:course_id => l.course_id, :lesson_id => l.id ) %></li>
                  <% count = count + 1 %>
               <% end %>
             </ul>
        </div>
    </div>
<% end %>

app/views/lessons/edit.html.erb
<div class="page-header">
<h1 class="page-title"><%=  link_to(@course.title, courses_showdetail_path(@course)) %> - New Lesson</h1>
</div>

<%= render 'form' %>

app/views/lessons/index.html.erb
<div class="page-header">
<h1 class="page-title">Lessons - <span class="post-title"><%= link_to @course_title, edit_course_path(@course_id) %></span></h1>
</div>
<div class="blog-post">
     <div class="span12">
       <% count = 1 %>
       <% @lessons.each do |lesson| %>
             <div class="row">
                    <h3 class="post-title"><%= count %>. <%= link_to lesson.title, lessons_display_lesson_path(:lesson_id => lesson.id ) %>
                    </h3>
             </div>
             <div class="row">
                    <p>
                      <%= raw lesson.description %>
                    </p>
             </div>
             <div class="row">
                  <div class="span2"><p></p></div>
                  <div class="span10">
                    <%= link_to 'Edit', edit_lesson_path(lesson), :class => 'btn' %>
                    <%= link_to 'Show', lessons_display_lesson_path(:lesson_id => lesson.id ), :class => 'btn btn-success' %>
                    <%= link_to 'Materials (' + lesson.material_ids.count.to_s() + ')', edit_lesson_path(lesson), :class => 'btn btn-primary' %>
                    <%= link_to 'Destroy', lesson, confirm: 'Are you sure?', method: :delete, :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
                  </div>
             </div>
             <% count = count + 1 %>
            <hr>
       <% end %>
     </div>
</div>

<br />

<%= link_to 'New Lesson', new_lesson_path(:course_id => @course_id, :course_title => @course_title), :class => 'btn btn-primary' %>

app/views/lessons/new.html.erb
<div class="page-header">
<h1 class="page-title"><%=  link_to(@course.title, courses_showdetail_path(@course)) %> - New Lesson</h1>
</div>

<%= render 'form' %>

app/views/lessons/show.html.erb
<div class="page-header">
<h1 class="page-title"><%= link_to @lesson.course.title, @lesson.course %> - <%= @lesson.title %>
</h1>
</div>

<div class="span3">
  <div class="widget">
      <div class="accordion" id="accordion2">
          <div class="accordion-group">
            <div class="accordion-heading">
              <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
                Lessons
              </a>
            </div>
            <div id="collapseOne" class="accordion-body collapse in">
              <div class="accordion-inner">
                <div id="lessons">
                  <% @course.lessons.each do |l| %>
                     <li><%= link_to l.title, lesson_path(:course_id => @course.id) %></li>
                  <% end %>

                </div>
              </div>
            </div>
          </div>
      </div>
  </div>
</div>

<div class="span9">
<div class="row">
  <div class="span9">
    <div class="row">
      <div class="well">
        <p class="lead"><%= raw @lesson.description %></p>
      </div>
    </div>

    <% if @lesson.materials.count > 0 %>
             <div class="span8">
                   <% @lesson.materials.each do |material| %>
                     <div class="row">
                       <% if material.content_type == 1 %>
                          <%= raw material.detail_content %>
                       <% elsif material.content_type == 2 %>
                          <%= material..embedded_content %>
                       <% else %>
                           <i class="icon-file"></i>
                       <% end %>
                     </div>
                   <% end %>
             </div>
    <% end %>


  </div>

</div>


</div>