config/routes.rb
Vavant::Application.routes.draw do
  resources :materials

  mount Ckeditor::Engine => '/ckeditor'

  mount Ckeditor::Engine => "/ckeditor"

  get "courses/authored" => 'courses#authored', :as => 'courses_authored'
  get "courses/registered" => 'courses#registered', :as => 'courses_registered'

  get "courses/register/:course_id" => 'courses#register', :as => 'courses_register'
  get "courses/showdetail/:course_id" => 'courses#showdetail', :as => 'courses_showdetail'
  get "courses/changestatus" => 'courses#changestatus', :as => 'courses_changestatus'
  get "courses/mark_complete/:course_id" => 'courses#mark_complete', :as => 'courses_mark_complete'
  get "courses/mark_incomplete/:course_id" => 'courses#mark_incomplete', :as => 'courses_mark_incomplete'

  get "tags/:tag" => 'home#index', :as => 'tag'

  get "lessons/associate_material" => 'lessons#associate_material', :as => 'lessons_associate_material'
  get "lessons/mark_complete/" => 'lessons#mark_complete', :as => 'lessons_mark_complete'
  get "lessons/mark_incomplete/" => 'lessons#mark_incomplete', :as => 'lessons_mark_incomplete'
  get "lessons/display_lesson" => 'lessons#display_lesson', :as => 'lessons_display_lesson'

  resources :courses

  resources :reviews

  resources :registrations

  resources :lessons

  resources :collections

  resources :languages

  devise_for :users

  root :to => 'home#index'

  get "home/userinfo" => 'home#userinfo', :as => 'home_userinfo'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]

  def index
      @courses = Course.all.page(params[:page])
  end

  def authored
    if (params[:collection_id].nil?)
      @courses = Course.courses_authored_by_user(current_user.id).page(params[:page])
    else
      @courses = Course.courses_authored_by_user_by_collection(current_user.id, params[:collection_id]).page(params[:page])
    end
  end

  def registered
    @registered_courses = Registration.user_registrations(current_user.id).page(params[:page])
  end

  def register
    @register = Registration.new(:user_id => current_user.id, :course_id => params[:course_id])
    if @register.save
        redirect_to(course_path(:id => params[:course_id]), :notice => 'You have successfully registered for the course.')
    end
  end

  def mark_complete
    @completion = Completion.find(:all, :conditions => ["course_id = ? and user_id = ? and lesson_id is NULL", params[:course_id], current_user.id])
    if (@completion.empty?)
      @completion = Completion.new(:user_id => current_user.id, :course_id => params[:course_id], :status => 2)
      if @completion.save
          redirect_to(course_path(:id => params[:course_id]), :notice => 'Course has been mark completed')
      end
    else
      @completion[0].status = 2
      if @completion[0].save
          redirect_to(course_path(:id => params[:course_id]), :notice => 'Course has been mark completed')
      end
    end
  end

  def mark_incomplete
    @completion = Completion.find(:all, :conditions => ["course_id = ? and user_id = ? and lesson_id is NULL", params[:course_id], current_user.id])
    if (@completion.empty?)
      @completion = Completion.new(:user_id => current_user.id, :course_id => params[:course_id], :status => 1)
      if @completion.save
          redirect_to(course_path(:id => params[:course_id]), :notice => 'Course has been marked in progress')
      end
    else
      @completion[0].status = 1
      if @completion[0].save
          redirect_to(course_path(:id => params[:course_id]), :notice => 'Course has been marked in progress')
      end

    end

  end

  def show
    @course = Course.find(params[:id])
    @course.reviews = Review.reviews_by_courses(@course.id)

    @is_user_registered = false
    if (current_user)
      @is_user_registered = Registration.is_user_registered_for_course(@course.id, current_user.id)

      @review = Review.new()
      @review.course_id = @course.id
      @review.user_id = current_user.id

      @all_completion = Completion.completions_by_course_and_user(@course.id, current_user.id)
    end

    @recommended_courses = @course.recommended_courses()
  end

  def showdetail
    @course = Course.find(params[:course_id])
    @course.reviews = Review.reviews_by_courses(@course.id)
  end

  def new
    @course = Course.new

    @collections_list = Collection.find_collection_name_by_user(current_user.id)
  end

  def changestatus
    @course = Course.find(params[:id])
    if (params[:status] == 'U')
      @course.enabled = false
    else
      @course.enabled = true
    end

    if @course.save
        redirect_to(courses_showdetail_path(@course), :notice => 'Course was successfully updated.')
    else
        render :action => "showdetail"
    end

  end

  def edit
    @course = Course.find(params[:id])

    @collections_list = Collection.find_collection_name_by_user(current_user.id)
  end

  def create
    @course = Course.new(params[:course])
    @course.user_id = current_user.id

    if @course.save
        redirect_to(courses_authored_path, :notice => 'Course was successfully created.')
    else
        render :action => "new"
    end

  end

  def update
    @course = Course.find(params[:id])

    if @course.update_attributes(params[:course])
        redirect_to(courses_authored_path, :notice => 'Course was successfully updated.')
    else
        render :action => "new"
    end
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    if (@course.errors.nil?)
      redirect_to(courses_authored_path, :notice => 'Course was successfully deleted.')
    else
      redirect_to(courses_authored_path, :alert => @course.errors[:base][0])
    end
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= semantic_form_for @course, :html => { :multipart => true } do |f| %>
  <%= f.inputs do %>
    <%= f.input :title, :input_html => { :class => "span12"} %>
    <%= f.input :description, :as => :ckeditor, :input_html => { :toolbar => 'Easy'} %>
    <%= f.input :price, :as => :number, :input_html => { :class => "span1" }, :prepend => '$' %>
    <%= f.input :language, :include_blank => false, :input_html => { :class => "span2"}  %>
    <%= f.input :tag_list, :label => 'Tags (comma separated)', :input_html => { :class => "span6"} %>
    <%= f.input :collection_name, :label => 'Collection', :input_html => { :class => "span3"} %>
    <% if !@course.id.nil? %>
        <%= image_tag @course.photo.url(), :size => "200x200" %><p><br></p>
    <% end %>
    <%= f.file_field :photo %>
    <%= f.input :enabled, :label => 'Enable?'%>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input, :label => 'Save' %>
  <% end %>
<% end %>

app/views/courses/authored.html.erb
<div class="page-header">
<h1 class="page-title">My Courses</h1>
</div>


<div class="blog-post">
     <div class="span12">
     <% @courses.each do |course| %>
       <div class="row">
              <h3 class="post-title"><%= link_to course.title, courses_showdetail_path(course) %>
                <% if course.price == 0.0 %>
                     <span class="price-color">- FREE</span>
                <% else %>
                     <span class="price-color">- $ <%= course.price %></span>
                <% end %>
              </h3>
       </div>
       <div class="row">
              <p>
                <% if course.enabled %>
                    <span class="label label-success">Published</span>
                <% else %>
                    <span class="label label-warning">Draft</span>
                <% end %>
                | <i class="icon-calendar"></i> <%= course.updated_at.to_date.to_s(:long) %>
                | <i class="icon-comment"></i><%= course.no_of_reviews %> comments</li>
                | <%= course.rating %> stars of 5.0</li>
                | <i class="icon-share"></i><%= course.no_of_registrations %> registered
                <% if course.collection_id.nil? %>
                <% else %>
                    | <i class="icon-folder-open"></i> <%= link_to course.collection_name, courses_authored_path(:collection_id => course.collection_id) %>
                <% end %>
                | <i class="icon-volume-up"></i> <%= course.language.name %>
              </p>
       </div>
       <div class="row">
               <p>
                 <% if course.tag_list.size > 0 %>
                     <i class="icon-tags"></i> Tags:
                     <% course.tag_list.each do |t| %>
                         <%= link_to t, tag_path(t), :class => "label label-info" %>
                     <% end %>
                 <% end %>
               </p>
       </div>
       <div class="row">
            <div class="span2">
              <%= image_tag course.photo.url(), :size => "100x100", :class => 'thumbnail' %>
            </div>
            <div class="span10">
              <p>
                <%= raw course.description %>
              </p>
            </div>
       </div>
       <hr>
    <% end %>
    <div class="row">
        <%= will_paginate @courses, :container => false %>
    </div>
    </div>
</div>

app/views/courses/edit.html.erb
<div class="page-header">
<h1 class="page-title">Edit Course</h1>
</div>

<%= render 'form' %>

app/views/courses/index.html.erb
<h1>Listing courses</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Price</th>
    <th>Rating</th>
    <th>Enabled</th>
    <th>User</th>
    <th>Collection</th>
    <th>Language</th>
    <th>No of reviews</th>
    <th>No of registrations</th>
    <th>Photo file name</th>
    <th>Photo content type</th>
    <th>Photo file size</th>
    <th>Photo updated at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @courses.each do |course| %>
  <tr>
    <td><%= course.title %></td>
    <td><%= course.description %></td>
    <td><%= course.price %></td>
    <td><%= course.rating %></td>
    <td><%= course.enabled %></td>
    <td><%= course.user_id %></td>
    <td><%= course.collection_id %></td>
    <td><%= course.language_id %></td>
    <td><%= course.no_of_reviews %></td>
    <td><%= course.no_of_registrations %></td>
    <td><%= course.photo_file_name %></td>
    <td><%= course.photo_content_type %></td>
    <td><%= course.photo_file_size %></td>
    <td><%= course.photo_updated_at %></td>
    <td><%= link_to 'Show', course %></td>
    <td><%= link_to 'Edit', edit_course_path(course) %></td>
    <td><%= link_to 'Destroy', course, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<div class="page-header">
<h1 class="page-title">New Course</h1>
</div>

<%= render 'form' %>

app/views/courses/registered.html.erb
<div class="page-header">
<h1 class="page-title">Registered Courses</h1>
</div>

<div class="blog-post">
<div class="span12">
 <% @registered_courses.each do |registration| %>
        <div class="row">
           <h3 class="post-title"><%= link_to registration.course.title, registration.course %>
             <% if registration.price == 0.0 %>
                  <span class="price-color">- FREE </span>
             <% else %>
                  <span class="price-color">- $ <%= registration.price %> </span>
             <% end %>
             <small>(registered on: <%= registration.created_at.to_date.to_s(:long) %>)</small>
           </h3>
        </div>
        <div class="row">
           <p>
             <i class="icon-user"></i> by <%= link_to registration.course.user.username, home_userinfo_path(:username => registration.course.user.username) %>
             | <i class="icon-calendar"></i> <%= registration.course.updated_at.to_date.to_s(:long) %>
             | <i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i>(<%= registration.course.no_of_reviews %> comments)
             | <i class="icon-share"></i><%= registration.course.no_of_registrations %> registered
             <% if registration.course.collection_id.nil? %>
             <% else %>
                 | <i class="icon-folder-open"></i> <%= registration.course.collection_name %>
             <% end %>
             | <i class="icon-volume-up"></i> <%= registration.course.language.name %>
           </p>
        </div>
        <div class="row">
            <p>
              <% if registration.course.tag_list.size > 0 %>
                  <i class="icon-tags"></i> Tags:
                  <% registration.course.tag_list.each do |t| %>
                      <%= link_to t, tag_path(t), :class => "label label-info" %>
                  <% end %>
              <% end %>
            </p>
        </div>
        <div class="row">
          <div class="span2">
            <%= image_tag registration.course.photo.url(), :size => "100x100", :class => 'thumbnail' %>
          </div>
          <div class="span10">
            <p>
              <%= raw registration.course.description %>
            </p>
          </div>
        </div>
         <div class="row">
           <div class="span2"><p></p></div>
           <div class="span10">
             <%= link_to 'Launch Lessons', lessons_display_lesson_path(:course_id => registration.course.id, :lesson_id => registration.course.lessons[0].id), :class => 'btn btn-large btn-info' %>
             <%= link_to 'Post a comment', registration.course(:anchor => 'post_comment'), :class => 'btn btn-large btn-warning' %>
           </div>
         </div>
        <hr>
  <% end %>
 <div class="row">
   <%= will_paginate @registered_courses, :container => false %>
 </div>
</div>
</div>

app/views/courses/show.html.erb
<div class="page-header">
<h1 class="page-title"><%= @course.title %>
  <% if @course.price == 0.0 %>
       <span class="price-color">- FREE</span>
  <% else %>
       <span class="price-color">- $ <%= @course.price %></span>
  <% end %>
</h1>
</div>

<div class="span12">
<div class="row">
  <div class="span9">
    <div class="row">
        <p></p>
        <p class="lead"><%= image_tag @course.photo.url(), :size => "100x100", :class => 'img-polaroid' %> <%= raw @course.description %></p>
    </div>

    <% if @course.lessons.count > 0 %>
               <div class="row">
                 <h3>Table of Contents</h3>
                   <table class="table table-bordered table-hover">
                       <tr>
                           <th>No.</th>
                           <th>Title</th>
                           <th>Attached File</th>
                           <% if @is_user_registered %>
                             <th>Status</th>
                           <% end %>

                       </tr>

                       <% count = 1 %>
                       <% @course.lessons.each do |lesson| %>
                           <tr>
                             <td><%= count %>.</td>
                             <% if @is_user_registered %>
                                <td><%= link_to lesson.title, lessons_display_lesson_path(:course_id => lesson.course_id, :lesson_id => lesson.id ) %></td>
                             <% else %>
                                <td><%= lesson.title %></td>
                             <% end %>
                             <td>
                               <% if lesson.material_file_name.nil? %>
                                    none
                               <% else %>
                                   <%= image_tag(Ckeditor::Utils.filethumb(lesson.material_file_name), :size => "20x20") %>
                                   <%= lesson.material_file_name %>
                               <% end %>
                             </td>
                             <% if @is_user_registered %>
                                 <% lesson_completion = nil %>
                                 <% if !@all_completion.empty? %>
                                     <% lesson_completion = @all_completion.detect{|c| c.lesson_id == lesson.id} %>
                                 <% end %>
                                 <% if lesson_completion.nil?  %>
                                     <td>-</td>
                                 <% elsif lesson_completion.status == 1 %>
                                     <td><i class="icon-arrow-right"></i> In Progress</td>
                                 <% else %>
                                     <td><i class="icon-ok"></i> Complete <small>(on <%= lesson_completion.updated_at.to_date.to_s(:long) %>)</small></td>
                                 <% end %>

                             <% end %>
                           </tr>
                           <% count = count + 1 %>
                       <% end %>
                   </table>
               </div>
    <% end %>

    <% if @course.reviews.count > 0 %>
        <a id="comments"></a>
        <br><br><br><br>
        <div class="row">
          <h3>Comments (<%= @course.reviews.count %>)</h3>

            <% @course.reviews.each do |review| %>

                <div class="comment-meta">
                  <%= link_to review.user.username, @review %> - <%= review.created_at.to_date.to_s(:long) %>
                  <% if review.rating == 1.0 %>
                    <p><i class="icon-star"></i></p>
                  <% elsif review.rating == 2.0 %>
                    <p><i class="icon-star"></i><i class="icon-star"></i></p>
                  <% elsif review.rating == 3.0 %>
                    <p></p><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i></p>
                  <% elsif review.rating == 4.0 %>
                    <p><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i></p>
                  <% elsif review.rating == 5.0 %>
                    <p><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i></p>
                  <% end %>
                </div>
                <div class="comment-body">
                  <p><%= review.comment %></p>
                </div>
            <% end %>

        </div>

        <hr>
    <% end %>

    <% if @is_user_registered %>
        <br><br><br><br>
        <a id="post_comment"></a>
        <div class="row">

            <div class="well">

              <%= semantic_form_for @review, :html => { :multipart => true } do |f| %>
                <%= f.inputs do %>
                  <%= f.input :rating, :as => :select, :collection => [["1 star", 1], ["2 stars", 2], ["3 stars", 3], ["4 stars", 4], ["5 stars", 5]], :input_html => { :class => "span2"}%>
                  <%= f.input :comment, :input_html => { :class => "span8"} %>
                  <%= f.input :course_id, :as => :hidden  %>
                  <%= f.input :user_id, :as => :hidden %>
                <% end %>

                <%= f.actions do %>
                  <%= f.action :submit, :as => :input, :label => 'Post Comment' %>
                <% end %>
              <% end %>
           </div>
        </div>
    <% end %>

  </div>

  <div class="span3">
      <% if @is_user_registered %>
        <p><%= link_to 'Launch Lessons', lessons_display_lesson_path(:course_id => @course.id, :lesson_id => @course.lessons[0].id), :class => 'btn btn-info' %></p>
        <p><%= link_to 'Post a comment', {:anchor => 'post_comment'}, :class => 'btn btn-warning' %></p>
      <% else %>
        <% if @course.price > 0 %>
            <%= link_to '$ ' + @course.price.to_s + ' - Register', courses_register_path(@course), :class => 'btn btn-success' %>
        <% else %>
            <%= link_to 'FREE - Register', courses_register_path(@course), :class => 'btn btn-success' %>
        <% end %>
      <% end %>
      <div class="widget">
           <h5 class="sidebar-title">Details </h5>
           <ul class="unstyled">
            <li>
            </li>
            <li><i class="icon-user"></i> by <%= link_to @course.user.username, home_userinfo_path(:username => @course.user.username) %></li>
            <li><i class="icon-calendar"></i> <%= @course.updated_at.to_date.to_s(:long) %> </li>
            <li><i class="icon-volume-up"></i><%= link_to  @course.language.name, root_path(:language_name =>  @course.language.name) %></li>
            <li><i class="icon-comment"></i><%= link_to @course.no_of_reviews, {:anchor => 'comments'} %> comments </li>
            <li><%= @course.rating %> stars of 5.0</li>
            <li><i class="icon-share"></i><%= @course.no_of_registrations %> registered</li>
            <% if @course.collection_id.nil? %>
            <% else %>
                 <i class="icon-calendar"></i><%= link_to @course.collection_name, root_path(:collection_id =>  @course.collection_id, :collection_name => @course.collection_name) %>
            <% end %>
            <% if @is_user_registered %>
                 <% if !@all_completion.empty? %>
                     <% course_completion = @all_completion.detect{|c| c.lesson_id.nil?} %>
                 <% end %>
                 <% if @all_completion.empty? || course_completion.status == 1  %>
                     <i class="icon-arrow-right"></i>In Progress
                     <li><small>(<%= link_to 'click', courses_mark_complete_path(:course_id => @course.id) %> to complete</small>)</li>
                 <% else %>
                     <li><i class="icon-ok"></i> on <%=  course_completion.updated_at.to_date.to_s(:long) %></li>
                     <li><small>(<%= link_to 'click', courses_mark_incomplete_path(:course_id => @course.id) %> to mark in progress</small>)</li>
                 <% end %>
            <% end %>

           </ul>
      </div>

      <div class="widget">
       <h5 class="sidebar-title">Tags </h5>
        <% if @course.tag_list.size > 0 %>
            <% @course.tag_list.each do |t| %>
                <%= link_to t, tag_path(t), :class => "label label-info" %>
            <% end %>
        <% end %>
      </div>

      <div class="widget">
        <h5 class="sidebar-title">Share </h5>
        <!-- AddThis Button BEGIN -->
        <div class="addthis_toolbox addthis_default_style">
        <a class="addthis_button_preferred_1"></a>
        <a class="addthis_button_preferred_2"></a>
        <a class="addthis_button_preferred_3"></a>
        <a class="addthis_button_preferred_4"></a>
        <a class="addthis_button_compact"></a>
        <a class="addthis_counter addthis_bubble_style"></a>
        </div>
        <script type="text/javascript" src="http://s7.addthis.com/js/300/addthis_widget.js#pubid=ra-508ed2dd07037dfe"></script>
        <!-- AddThis Button END -->
      </div>
      <% if @recommended_courses.length > 0 %>
          <h5 class="sidebar-title">Recommended Courses</h5>
          <div class="well">
              <table class="table table-striped">
                <% @recommended_courses.each do |course| %>
                    <tr>
                        <td width="40%"><%= image_tag course.photo.url(), :size => "50x50", :class => 'img-polaroid' %></td>
                        <td width="60%"><%= link_to course.title, course %><br><%= course.no_of_registrations %> registered<br><%= course.rating %> stars<br>by <%= link_to course.user.username, course %></td>
                    </tr>
                <% end %>
              </table>
          </div>
      <% end %>

  </div>
</div>


</div>

app/views/courses/showdetail.html.erb
<div class="page-header" xmlns="http://www.w3.org/1999/html">
<h1 class="page-title"><%= @course.title %>
  <% if @course.price == 0.0 %>
       <span class="price-color">- FREE</span>
  <% else %>
       <span class="price-color">- $ <%= @course.price %></span>
  <% end %>
</h1>
</div>

<div class="span12">
<div class="row">
  <div class="span9">
    <div class="row">
        <p></p>
        <p class="lead"><%= image_tag @course.photo.url(), :size => "100x100", :class => 'img-polaroid' %> <%= raw @course.description %></p>
    </div>

    <% if @course.lessons.count > 0 %>
               <div class="row">
                 <h3>Table of Contents</h3>
               <table class="table table-bordered table-hover">
                   <tr>
                       <th>No.</th>
                       <th>Title</th>
                       <th>Attached File</th>
                       <th>Actions</th>
                   </tr>

                   <% count = 1 %>
                   <% @course.lessons.each do |lesson| %>
                       <tr>
                         <td><%= count %>.</td>
                         <td><%= lesson.title %></td>
                         <td>
                           <% if lesson.material_file_name.nil? %>
                                none
                           <% else %>
                               <%= image_tag(Ckeditor::Utils.filethumb(lesson.material_file_name), :size => "20x20") %>
                               <%= lesson.material_file_name %>
                           <% end %>
                         </td>
                         <td>
                           <%= link_to 'Edit', edit_lesson_path(lesson), :class => 'btn btn-mini' %>
                           <%= link_to 'Destroy', lesson, method: :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
                         </td>
                       </tr>
                       <% count = count + 1 %>
                   <% end %>
               </table>
               </div>
    <% end %>


  </div>

  <div class="span3">
    <div class="btn-group">
      <a class="btn btn-primary" href="#"><i class="icon-tasks icon-white"></i> Actions</a>
      <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>

      <ul class="dropdown-menu">
        <li><%= link_to 'Show Course', course_path(@course) %></li>
        <li><%= link_to 'Edit Course', edit_course_path(@course) %></li>
        <li><%= link_to 'Delete Course', @course, method: :delete, :confirm => 'Are you sure?' %></li>
        <li class="divider"></li>
        <li><%= link_to 'Add Lesson', new_lesson_path(:course_id => @course.id) %></li>
        <li class="divider"></li>
        <% if @course.enabled %>
            <li><%= link_to 'Change to Draft', courses_changestatus_path(:id => @course.id, :status => 'U') %></li>
        <% else %>
            <li><%= link_to 'Publish', courses_changestatus_path(:id => @course.id, :status => 'P') %></li>
        <% end %>
      </ul>
    </div><!-- /btn-group -->

      <div class="widget">
           <h5 class="sidebar-title">Details </h5>
           <ul class="unstyled">
            <li>
            </li>
             <li><strong>Status: </strong>
               <% if @course.enabled %>
                  <span class="label label-success">Published</span>
              <% else %>
                  <span class="label label-warning">Not Published</span>
              <% end %>
             </li>
            <li><i class="icon-user"></i> by <%= @course.user.username %></li>
            <li><i class="icon-calendar"></i> <%= @course.updated_at.to_date.to_s(:long) %> </li>
            <li><i class="icon-volume-up"></i><%= @course.language.name %></li>
            <li><i class="icon-comment"></i><%= @course.no_of_reviews %> comments</li>
            <li><%= @course.rating %> stars of 5.0</li>
            <li><i class="icon-share"></i><%= link_to @course.no_of_registrations.to_s() + ' registered', registrations_path(:course_id => @course.id) %></li>
            <% if @course.collection_id.nil? %>
            <% else %>
                 <i class="icon-calendar"></i><%= @course.collection_name %>
            <% end %>
           </ul>
      </div>

      <div class="widget">
       <h5 class="sidebar-title">Tags </h5>
        <% if @course.tag_list.size > 0 %>
            <% @course.tag_list.each do |t| %>
                <span class="label label-info"><%= t %></span>
            <% end %>
        <% end %>
      </div>

  </div>
</div>


</div>