config/routes.rb
Vavant::Application.routes.draw do
  resources :materials

  mount Ckeditor::Engine => '/ckeditor'

  mount Ckeditor::Engine => "/ckeditor"

  get "courses/authored" => 'courses#authored', :as => 'courses_authored'
  get "courses/registered" => 'courses#registered', :as => 'courses_registered'

  get "courses/register/:course_id" => 'courses#register', :as => 'courses_register'
  get "courses/showdetail/:course_id" => 'courses#showdetail', :as => 'courses_showdetail'
  get "courses/changestatus" => 'courses#changestatus', :as => 'courses_changestatus'
  get "courses/mark_complete/:course_id" => 'courses#mark_complete', :as => 'courses_mark_complete'
  get "courses/mark_incomplete/:course_id" => 'courses#mark_incomplete', :as => 'courses_mark_incomplete'

  get "tags/:tag" => 'home#index', :as => 'tag'

  get "lessons/associate_material" => 'lessons#associate_material', :as => 'lessons_associate_material'
  get "lessons/mark_complete/" => 'lessons#mark_complete', :as => 'lessons_mark_complete'
  get "lessons/mark_incomplete/" => 'lessons#mark_incomplete', :as => 'lessons_mark_incomplete'
  get "lessons/display_lesson" => 'lessons#display_lesson', :as => 'lessons_display_lesson'

  resources :courses

  resources :reviews

  resources :registrations

  resources :lessons

  resources :collections

  resources :languages

  devise_for :users

  root :to => 'home#index'

  get "home/userinfo" => 'home#userinfo', :as => 'home_userinfo'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Vavant</title>
  <%= stylesheet_link_tag    "font-awesome", "style", "colorbox", "application", :media => "all" %>
  <%= javascript_include_tag "application", "/assets/ckeditor/", "/assets/jwplayer" %>
  <script>jwplayer.key="W3awPD5KTAwHFjcxRwWo+Cda++KU+OEBlm5rZg=="</script>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="brand" href="/">vavant</a>
        <div class="nav-collapse collapse">
            <ul class="nav pull-right">
              <li><%= link_to "Create Course", new_course_path %></li>
              <% if user_signed_in? %>
                  <li class='dropdown-toggle' data-toggle='dropdown'><%= link_to current_user.username, '' %></li>
                      <ul class="dropdown-menu">
                        <li><%= link_to "Profile", edit_user_registration_path %></li>
                        <li class="divider"></li>
                        <li><%= link_to "Registered Courses", courses_registered_path %></li>
                        <li class="divider"></li>
                        <li><%= link_to "My Courses", courses_authored_path %></li>
                        <li><%= link_to "My Collections", collections_path %></li>
                        <li><%= link_to "My Materials", materials_path %></li>
                        <li class="divider"></li>
                        <li><%= link_to "Sign Out", destroy_user_session_path %></li>
                      </ul>
              <% else %>
                <li><%= link_to "Sign Up", new_user_registration_path %></li>
                <li><%= link_to "Sign In", new_user_session_path %></li>
              <% end %>
            </ul>
            <form class="navbar-search" action="/">
              <input type="text" class="search-query" placeholder="Find Courses" name="find_course_by">
            </form>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
        <% flash.each do |name, msg| %>
          <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
            <a class="close" data-dismiss="alert">x</a>
            <%= msg  %>
          </div>
        <% end %>
        <%= yield %>
    </div>

     <footer class="footer">
       <div class="container">
          <div class="row">
            <div class="span12" align="center">
          &copy; Company 2012 | <%= link_to 'what is vavant', root_path %> | <a href="#">About Us</a> | <a href="#">Privacy Policy</a> | <a href="#">Terms of Use</a> | <a href="#">Contact Us</a>
            </div>
          </div>
       </div>
     </footer>
  </div>

</body>
</html>